---
title: "Code Book"
author: "Oscar Ramirez"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  markdown: 
    wrap: sentence
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The *run_analysis.R* script prepares the data and then performs required processes in accord to the course's evaluation criteria.
A 5-step process is executed:

1.  **Download the dataset**
    -   A zip file is downloaded and extracted to a folder named **UCI HAR Dataset**.
2.  **Assign each data to variables**
    -   features: contains data from *features.txt*, 6 rows, 2 columns. The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ.
    -   activities: contains data from *activity_labels.txt*, 2947 rows, 1 column. List of activities performed when the corresponding measurements were taken and its codes (labels).
    -   subject_test: contains data from *test/subject_test.txt*, 2947 rows, 1 column. Test data of 9/30 volunteer test subjects being observed.
    -   x_test: contains data from *test/X_test.txt*, 2947 rows, 561 columns. Recorded features test data.
    -   y_test: contains data from *test/y_test.txt*, 2947 rows, 1 columns. Test data of activities' code labels.
    -   subject_train: contains data from *test/subject_train.txt*, 7352 rows, 1 column. Train data of 21/30 volunteer subjects being observed
    -   x_train: contains data from *test/X_train.txt*, 7352 rows, 561 columns. Recorded features train data.
    -   y_train: contains data from *test/y_train.txt*, 7352 rows, 1 columns. Train data of activities' code labels.
3.  **Merges the training and the test sets to create one data set**
    -   X (10299 rows, 561 columns) is created by merging x_train and x_test using rbind() function.
    -   Y (10299 rows, 1 column) is created by merging y_train and y_test using rbind() function.
    -   Subject (10299 rows, 1 column) is created by merging subject_train and subject_test using rbind() function.
    -   dataMerged (10299 rows, 563 column) is created by merging Subject, Y and X using cbind() function.
4.  **Extracts only the measurements on the mean and standard deviation for each measurement**
    -   dataTidy (10299 rows, 88 columns) is created by subsetting dataMerged, selecting only columns: subject, code and the measurements on the mean and standard deviation (std) for each measurement.
5.  **Uses descriptive activity names to name the activities in the data set**
    -   Entire numbers in code column of the dataTidy replaced with corresponding activity taken from second column of the activities variable.
6.  **Appropriately labels the data set with descriptive variable names**
    -   code column in TidyData renamed into activities
    -   All Acc in column's name replaced by Accelerometer
    -   All Gyro in column's name replaced by Gyroscope
    -   All BodyBody in column's name replaced by Body
    -   All Mag in column's name replaced by Magnitude
    -   All start with character f in column's name replaced by Frequency
    -   All start with character t in column's name replaced by Time
7.  **From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject**
    -   dataFinal (180 rows, 88 columns) is created by summarizing TidyData taking the means of each variable for each activity and each subject, after grouped by subject and activity.
    -   Export dataFinal into FinalData.txt file.
